'use strict';
const assert=require('assert'); const fs=require('fs'); const os=require('os'); const path=require('path');
process.env.BOT_DATA_DIR=fs.mkdtempSync(path.join(os.tmpdir(),'nofun-provider-'));
process.env.PROVIDER_SECRET_KEY='test-key-only-not-production';
const importRuns=require('../src/league/importRunService');
const pcs=require('../src/services/providerConnectionService');
const syncRuns=require('../src/services/providerSyncRunService');
let p=0,f=0; async function t(n,fn){try{await fn();console.log('✅',n);p++;}catch(e){console.error('❌',n,e.stack||e);f++;}}
(async()=>{
 await t('receipt artifact is durable before acknowledgement',()=>{const body=JSON.stringify({games:[{week:1,team1:'A',team2:'B'}]});const hash=importRuns.hashPayload(body);const r=importRuns.recordReceipt({provider:'companion_export',leagueId:'L1',leagueToken:'secret',payloadHash:hash,size:Buffer.byteLength(body),rawPayload:body});assert.equal(r.durable,true);assert.equal(importRuns.getArtifact(hash),body);assert(importRuns.listByStatus('companion_export',['received']).some(x=>x.id===r.run.id));});
 await t('duplicate delivery does not create a second import run',()=>{const body='{"x":1}',hash=importRuns.hashPayload(body);const a=importRuns.recordReceipt({provider:'x',leagueId:'L1',leagueToken:'t',payloadHash:hash,rawPayload:body});const b=importRuns.recordReceipt({provider:'x',leagueId:'L1',leagueToken:'t',payloadHash:hash,rawPayload:body});assert.equal(a.duplicate,false);assert.equal(b.duplicate,true);assert.equal(a.run.id,b.run.id);});
 await t('artifact cap matches six MiB gateway contract',()=>{const ok='a'.repeat(3*1024*1024),bad='b'.repeat(6*1024*1024+1);assert.equal(importRuns.storeArtifact(importRuns.hashPayload(ok),ok).stored,true);assert.equal(importRuns.storeArtifact(importRuns.hashPayload(bad),bad).stored,false);});
 await t('provider route token stored only as hash and resolves league',()=>{const up=pcs.upsertConnection({leagueId:'L1',providerKey:'companion_export',routeToken:true,status:'configured'});assert(up.routeToken);const raw=pcs.getConnection('L1','companion_export');assert(raw.routeTokenHash);assert(!JSON.stringify(raw).includes(up.routeToken));assert.equal(pcs.resolveRouteToken('companion_export',up.routeToken).leagueId,'L1');});
 await t('provider secret is encrypted at rest and decryptable only through service',()=>{pcs.upsertConnection({leagueId:'L1',providerKey:'custom_endpoint',secret:'top-secret'});const raw=pcs.getConnection('L1','custom_endpoint');assert(raw.secretCiphertext);assert(!raw.secretCiphertext.includes('top-secret'));assert.equal(pcs.getSecret('L1','custom_endpoint'),'top-secret');});

 await t('delayed provider revision cannot overwrite newer canonical resource',()=>{const snaps=require('../src/services/providerDataSnapshotService');const a=snaps.saveStage('neonsportz','teams',[{id:1}],{revision:20});const b=snaps.saveStage('neonsportz','teams',[{id:2}],{revision:19});assert.equal(b.ignoredStale,true);assert.equal(snaps.getStage('neonsportz','teams').data[0].id,1);});
 await t('rotated receiver token invalidates the old token',()=>{const first=pcs.upsertConnection({leagueId:'L2',providerKey:'companion_export',routeToken:true});const second=pcs.rotateRouteToken('L2','companion_export');assert.equal(pcs.resolveRouteToken('companion_export',first.routeToken).valid,false);assert.equal(pcs.resolveRouteToken('companion_export',second.routeToken).leagueId,'L2');});
 await t('activating one provider can leave only one authoritative active provider',()=>{pcs.upsertConnection({leagueId:'L3',providerKey:'neonsportz',status:'active'});pcs.upsertConnection({leagueId:'L3',providerKey:'custom_endpoint',status:'active'});pcs.deactivateOtherConnections('L3','custom_endpoint');const rows=pcs.listConnections('L3');assert.equal(rows.filter(x=>['active','degraded'].includes(x.status)).length,1);assert.equal(rows.find(x=>x.providerKey==='neonsportz').status,'ready');});
 await t('interrupted sync runs are terminalized on restart recovery',()=>{const r=syncRuns.start({leagueId:'L1',providerKey:'custom_endpoint'});assert.equal(syncRuns.recoverInterrupted()>=1,true);assert.equal(syncRuns.list({leagueId:'L1'}).find(x=>x.id===r.id).status,'failed');});

 await t('APP_ENV production requires durable provider connection persistence when JSON override is off',async()=>{const prevApp=process.env.APP_ENV,prevNode=process.env.NODE_ENV,prevDb=process.env.DATABASE_URL,prevOverride=process.env.ALLOW_JSON_PROVIDER_CONNECTIONS;process.env.APP_ENV='production';process.env.NODE_ENV='test';delete process.env.DATABASE_URL;delete process.env.ALLOW_JSON_PROVIDER_CONNECTIONS;pcs.upsertConnection({leagueId:'PROD1',providerKey:'custom_endpoint'});const r=await pcs.persistConnectionDurable('PROD1','custom_endpoint');assert.equal(r.ok,false);assert.equal(r.reason,'database-required-for-provider-connections');if(prevApp===undefined)delete process.env.APP_ENV;else process.env.APP_ENV=prevApp;if(prevNode===undefined)delete process.env.NODE_ENV;else process.env.NODE_ENV=prevNode;if(prevDb===undefined)delete process.env.DATABASE_URL;else process.env.DATABASE_URL=prevDb;if(prevOverride===undefined)delete process.env.ALLOW_JSON_PROVIDER_CONNECTIONS;else process.env.ALLOW_JSON_PROVIDER_CONNECTIONS=prevOverride;});
 await t('unscoped provider authority fails safe to local when multiple leagues exist',()=>{const active=require('../src/services/activeLeagueService');active.upsertLeague({id:'ML1',leagueName:'One',leagueTypeId:'madden',game:'madden'});active.upsertLeague({id:'ML2',leagueName:'Two',leagueTypeId:'madden',game:'madden'});const ps=require('../src/services/providerService');ps.setActiveProvider('custom_endpoint');assert.equal(ps.getActiveProvider().key,'local');});
 console.log(`\nProvider durability regression: ${p} passed, ${f} failed`); if(f)process.exitCode=1;
})();
