'use strict';
const assert=require('assert');const fs=require('fs');const os=require('os');const path=require('path');
process.env.BOT_DATA_DIR=fs.mkdtempSync(path.join(os.tmpdir(),'nofun-provider-contract-'));
process.env.PROVIDER_SECRET_KEY='provider-contract-test-key';process.env.APP_ENV='test';process.env.NODE_ENV='test';
let passed=0,failed=0;async function test(name,fn){try{await fn();console.log('✅',name);passed++;}catch(e){console.error('❌',name,'\n ',e.stack||e);failed++;}}
(async()=>{
 await test('unsupported provider controls return structured unsupported-capability',async()=>{const {createProvider}=require('../src/providers/gameProvider');const p=createProvider({key:'read_only_test',capabilities:{readSchedule:true}});const r=await p.advanceWeek({});assert.equal(r.ok,false);assert.equal(r.reason,'unsupported-capability');assert.equal(r.capability,'advanceWeek');});
 await test('provider connection state machine rejects illegal transitions',()=>{const pcs=require('../src/services/providerConnectionService');pcs.upsertConnection({leagueId:'SM1',providerKey:'custom_endpoint',status:'draft'});assert.throws(()=>pcs.transitionConnection('SM1','custom_endpoint','active'),/illegal-connection-transition/);});
 await test('provider secret AES-GCM tamper detection fails closed',()=>{const sec=require('../src/services/providerSecretService');const blob=sec.encrypt('very-secret');assert.equal(sec.decrypt(blob),'very-secret');const parts=blob.split(':');parts[3]=Buffer.from('tampered').toString('base64');assert.equal(sec.decrypt(parts.join(':')),null);assert.equal(sec.redact('very-secret'),'[secret configured]');});
 await test('Companion parser recognizes all implemented stages',()=>{const {detectStage}=require('../src/providers/madden/companion/parser');assert.equal(detectStage({leagueInfo:{}}),'league');assert.equal(detectStage({leagueTeamInfoList:[]}),'teams');assert.equal(detectStage({rosterInfoList:[]}),'roster');assert.equal(detectStage({gameScheduleInfoList:[]}),'schedule');assert.equal(detectStage({playerPassingStatInfoList:[]}),'stats');});
 await test('HTTP intake rejects private, credentialed, and non-HTTPS URLs',()=>{const {validateExternalUrl}=require('../src/utils/httpIntake');assert.equal(validateExternalUrl('https://127.0.0.1/x').reason,'private-destination');assert.equal(validateExternalUrl('https://user:pass@example.com/x').reason,'credentials-in-url');assert.equal(validateExternalUrl('http://example.com/x').reason,'protocol-not-allowed');assert.equal(validateExternalUrl('https://example.com/x').ok,true);});
 await test('HTTP intake never follows redirects automatically',async()=>{const {fetchExternal}=require('../src/utils/httpIntake');const headers={get:()=>null};const r=await fetchExternal({url:'https://example.com/a',fetchImpl:async()=>({status:302,ok:false,headers}),parse:'text'});assert.equal(r.ok,false);assert.equal(r.reason,'redirect-not-followed');});
 await test('HTTP intake enforces declared body cap before buffering',async()=>{const {fetchExternal}=require('../src/utils/httpIntake');const headers={get:k=>k==='content-length'?'1000':(k==='content-type'?'application/json':null)};const r=await fetchExternal({url:'https://example.com/a',maxBytes:10,expectedContentTypes:['application/json'],fetchImpl:async()=>({status:200,ok:true,headers,arrayBuffer:async()=>Buffer.from('{}')})});assert.equal(r.ok,false);assert.equal(r.reason,'max-bytes-exceeded');});
 await test('HTTP intake rejects unexpected content type',async()=>{const {fetchExternal}=require('../src/utils/httpIntake');const headers={get:k=>k==='content-type'?'text/html':null};const r=await fetchExternal({url:'https://example.com/a',expectedContentTypes:['application/json'],fetchImpl:async()=>({status:200,ok:true,headers,arrayBuffer:async()=>Buffer.from('{}')})});assert.equal(r.ok,false);assert.equal(r.reason,'unexpected-content-type');});
 await test('partial provider resource updates preserve last-known-good sibling resources',()=>{const snaps=require('../src/services/providerDataSnapshotService');snaps.saveStage('pc','teams',[{id:'T1'}],{revision:1});snaps.saveStage('pc','players',[{id:'P1'}],{revision:1});snaps.saveStage('pc','players',[{id:'P2'}],{revision:2});assert.equal(snaps.getStage('pc','teams').data[0].id,'T1');assert.equal(snaps.getStage('pc','players').data[0].id,'P2');});
 await test('provider projection source contains no workflow-week mutation authority',()=>{const src=fs.readFileSync(path.join(__dirname,'../src/services/providerProjectionService.js'),'utf8');assert(!/workflowWeek\s*=|lastAdvancedWeek\s*=/.test(src));});
 await test('Direct EA control remains disabled and unsupported',async()=>{const ea=require('../src/providers/madden/ea/controlProvider');assert.equal(ea.describe().verified,false);assert.equal(ea.getCapabilities().advanceWeek,false);const r=await ea.advanceWeek({});assert.equal(r.reason,'unsupported-capability');});
 console.log(`\nProvider contract regression: ${passed} passed, ${failed} failed`);if(failed)process.exitCode=1;
})();
