'use strict';
const assert=require('assert');const fs=require('fs');const os=require('os');const path=require('path');
process.env.BOT_DATA_DIR=fs.mkdtempSync(path.join(os.tmpdir(),'nofun-provider-faults-'));
process.env.PROVIDER_SECRET_KEY='test-key';process.env.APP_ENV='test';process.env.NODE_ENV='test';
const pcs=require('../src/services/providerConnectionService');
const imports=require('../src/league/importRunService');
const companion=require('../src/providers/madden/companion/exportGateway');
const neonWebhook=require('../src/providers/madden/neonsportz/webhook');
let passed=0,failed=0;async function t(n,fn){try{await fn();console.log('✅',n);passed++;}catch(e){console.error('❌',n,'\n ',e.stack||e);failed++;}}
(async()=>{
 await t('wrong receiver token is rejected without revealing token details',async()=>{pcs.upsertConnection({leagueId:'L1',providerKey:'companion_export',routeToken:true});const r=await companion.receiveExportDurable({leagueToken:'wrong-token-not-valid-1234',leagueId:'L1',contentType:'application/json',body:'{}'});assert.equal(r.status,404);assert.equal(r.body.reason,'not-found');});
 await t('malformed companion JSON is accepted only after durable receipt then terminally fails parse',async()=>{const up=pcs.upsertConnection({leagueId:'L2',providerKey:'companion_export',routeToken:true});const r=await companion.receiveExportDurable({leagueToken:up.routeToken,leagueId:'L2',contentType:'application/json',body:'{bad json'});assert.equal(r.status,202);const p=companion.processImportRun(r.importId);assert.equal(p.ok,false);assert(imports.listRecent(20).find(x=>x.id===r.importId&&x.status==='failed'));});
 await t('Neon webhook missing delivery ID is rejected',async()=>{const up=pcs.upsertConnection({leagueId:'L3',providerKey:'neonsportz',routeToken:true,externalLeagueId:'NL3'});const r=await neonWebhook.receiveImportCompletedDurable({routeToken:up.routeToken,headers:{},body:JSON.stringify({event:'league_import_completed',leagueId:'NL3'})});assert.equal(r.status,400);assert.equal(r.body.reason,'missing-delivery-id');});
 await t('Neon wrong external league is ignored without mutating queue',async()=>{const up=pcs.upsertConnection({leagueId:'L4',providerKey:'neonsportz',routeToken:true,externalLeagueId:'EXPECTED'});const before=imports.listByStatus('neonsportz',[]).length;const r=await neonWebhook.receiveImportCompletedDurable({routeToken:up.routeToken,headers:{'x-neonsportz-delivery':'d-wrong'},body:JSON.stringify({event:'league_import_completed',leagueId:'OTHER'})});assert.equal(r.status,200);assert.equal(r.body.reason,'unknown-league');assert.equal(imports.listByStatus('neonsportz',[]).length,before);});
 await t('Neon duplicate delivery is idempotent',async()=>{const up=pcs.upsertConnection({leagueId:'L5',providerKey:'neonsportz',routeToken:true,externalLeagueId:'NL5'});const req={routeToken:up.routeToken,headers:{'x-neonsportz-delivery':'delivery-1'},body:JSON.stringify({event:'league_import_completed',leagueId:'NL5',weekIndex:4})};const a=await neonWebhook.receiveImportCompletedDurable(req);const b=await neonWebhook.receiveImportCompletedDurable(req);assert.equal(a.status,202);assert.equal(b.status,200);assert.equal(b.duplicate,true);assert.equal(a.importId,b.importId);});
 await t('work queue finds an older target even after more than 50 newer receipts',async()=>{const body='{"games":[]}';const target=imports.recordReceipt({provider:'target-provider',leagueId:'L6',payloadHash:imports.hashPayload(body+'target'),rawPayload:body+'target'});imports.markStatus(target.run.id,'queued');for(let i=0;i<70;i++){const b=`{"n":${i}}`;const r=imports.recordReceipt({provider:'other-provider',leagueId:'L6',payloadHash:imports.hashPayload(b),rawPayload:b});imports.markStatus(r.run.id,'applied');}const rows=await imports.listRecoverableDurable('target-provider',['queued']);assert(rows.some(x=>x.id===target.run.id));});
 await t('Neon read client retries 429 and 5xx then succeeds',async()=>{const intake=require('../src/utils/httpIntake');const original=intake.fetchExternal;let calls=0;intake.fetchExternal=async()=>{calls++;if(calls===1)return{ok:false,reason:'bad-status',status:429,headers:{retryAfter:'0'}};if(calls===2)return{ok:false,reason:'bad-status',status:503,headers:{}};return{ok:true,status:200,headers:{},data:{currentWeek:1,weeks:{'1':[ {week:1,homeTeam:'A',awayTeam:'B'} ]}}};};process.env.NEONSPORTZ_SNAPSHOT_URL='https://example.com/neon.json';delete require.cache[require.resolve('../src/providers/madden/neonsportz/client')];const neon=require('../src/providers/madden/neonsportz/client');const h=await neon.healthCheck();intake.fetchExternal=original;delete process.env.NEONSPORTZ_SNAPSHOT_URL;assert.equal(h.ok,true);assert.equal(calls,3);});
 await t('stale resource revision cannot replace newer provider data',()=>{const snaps=require('../src/services/providerDataSnapshotService');snaps.saveStage('neonsportz','players',[{id:'new'}],{revision:50});const old=snaps.saveStage('neonsportz','players',[{id:'old'}],{revision:49});assert.equal(old.ignoredStale,true);assert.equal(snaps.getStage('neonsportz','players').data[0].id,'new');});
 console.log(`\nProvider faults regression: ${passed} passed, ${failed} failed`);if(failed)process.exitCode=1;
})();
