'use strict';
const assert=require('assert');
const trades=require('../src/services/tradeWorkflowService');
let passed=0,failed=0;
async function test(name,fn){try{await fn();console.log('✅',name);passed++;}catch(e){console.error('❌',name,'\n ',e.stack||e);failed++;}}
function makeState(rows){let n=1,persist=0;return{openTeamRegistry:rows,pendingTrades:new Map(),activeLeagues:new Map([['l1',{leagueName:'Sunday League'}],['l2',{leagueName:'Weeknight League'}]]),nextTradeId:()=>`TRADE-${String(n++).padStart(4,'0')}`,persistPendingState:()=>{persist++;},get persistCount(){return persist;}};}
(async()=>{
 await test('proposal normalizes configured teams and persists immediately',()=>{const s=makeState([{leagueId:'l1',baseTeam:'Ravens',displayTeam:'Baltimore Ravens',ownerId:'u1',isOpen:false},{leagueId:'l1',baseTeam:'Jets',displayTeam:'New York Jets',ownerId:'u2',isOpen:false}]);const r=trades.propose(s,{proposerId:'u1',yourTeam:'ravens',targetTeam:'jets',details:'Pick 1 for Player X',leagueId:'l1'});assert.equal(r.ok,true);assert.equal(r.trade.proposerTeam,'Baltimore Ravens');assert.equal(r.trade.targetBase,'Jets');assert.equal(s.pendingTrades.size,1);assert.equal(s.persistCount,1);});
 await test('proposal rejects a source team not owned by proposer',()=>{const s=makeState([{leagueId:'l1',baseTeam:'Ravens',displayTeam:'Ravens',ownerId:'u9',isOpen:false},{leagueId:'l1',baseTeam:'Jets',displayTeam:'Jets',ownerId:'u2',isOpen:false}]);const r=trades.propose(s,{proposerId:'u1',yourTeam:'Ravens',targetTeam:'Jets',details:'x',leagueId:'l1'});assert.equal(r.ok,false);assert.equal(r.reason,'proposer-does-not-own-source-team');});
 await test('proposal rejects unclaimed target',()=>{const s=makeState([{leagueId:'l1',baseTeam:'Ravens',displayTeam:'Ravens',ownerId:'u1',isOpen:false},{leagueId:'l1',baseTeam:'Jets',displayTeam:'Jets',ownerId:null,isOpen:true}]);const r=trades.propose(s,{proposerId:'u1',yourTeam:'Ravens',targetTeam:'Jets',details:'x',leagueId:'l1'});assert.equal(r.ok,false);assert.equal(r.reason,'target-team-is-unclaimed');});
 await test('proposal rejects same team',()=>{const s=makeState([{leagueId:'l1',baseTeam:'Ravens',displayTeam:'Ravens',ownerId:'u1',isOpen:false}]);const r=trades.propose(s,{proposerId:'u1',yourTeam:'Ravens',targetTeam:'Ravens',details:'x',leagueId:'l1'});assert.equal(r.ok,false);assert.equal(r.reason,'cannot-trade-with-same-team');});
 await test('multiple leagues require scope instead of guessing',()=>{const s=makeState([{leagueId:'l1',baseTeam:'Ravens',displayTeam:'Ravens',ownerId:'u1',isOpen:false},{leagueId:'l2',baseTeam:'Ravens',displayTeam:'Ravens',ownerId:'u1',isOpen:false},{leagueId:'l1',baseTeam:'Jets',displayTeam:'Jets',ownerId:'u2',isOpen:false},{leagueId:'l2',baseTeam:'Jets',displayTeam:'Jets',ownerId:'u3',isOpen:false}]);const r=trades.propose(s,{proposerId:'u1',yourTeam:'Ravens',targetTeam:'Jets',details:'x'});assert.equal(r.ok,false);assert.equal(r.reason,'league-ambiguous');});
 await test('decision is single-consume and persists deletion',()=>{const s=makeState([{leagueId:'l1',baseTeam:'Ravens',displayTeam:'Ravens',ownerId:'u1',isOpen:false},{leagueId:'l1',baseTeam:'Jets',displayTeam:'Jets',ownerId:'u2',isOpen:false}]);const p=trades.propose(s,{proposerId:'u1',yourTeam:'Ravens',targetTeam:'Jets',details:'x',leagueId:'l1'});const r=trades.decide(s,p.trade.tradeId,{approved:true,actorId:'comm'});assert.equal(r.ok,true);assert.equal(r.trade.status,'approved');assert.equal(s.pendingTrades.size,0);const again=trades.decide(s,p.trade.tradeId,{approved:false,actorId:'comm'});assert.equal(again.ok,false);assert.equal(again.reason,'already-processed-or-not-found');assert.equal(s.persistCount,2);});
 console.log(`\nTrade flow regression: ${passed} passed, ${failed} failed`);if(failed)process.exitCode=1;
})();
